<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CombustibleAPI.Api</RootNamespace>
    <UserSecretsId>a41d9b0e-9f2b-4b0a-8b6d-combustible-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CombustibleAPI.Application\CombustibleAPI.Application.csproj" />
    <ProjectReference Include="..\CombustibleAPI.Infrastructure\CombustibleAPI.Infrastructure.csproj" />
    <ProjectReference Include="..\CombustibleAPI.Domain\CombustibleAPI.Domain.csproj" />
  </ItemGroup>

</Project>
