BEGIN;

-- 1. TABLA: rol
 

CREATE TABLE rol (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL UNIQUE,
    descripcion VARCHAR(150),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

 
-- 2. TABLA: departamento
 

CREATE TABLE departamento (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(250),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ
);

 
-- 3. TABLA: tipo_combustible
 

CREATE TABLE tipo_combustible (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(150),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

 
-- 4. TABLA: estacion
 

CREATE TABLE estacion (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    ubicacion VARCHAR(200),
    descripcion VARCHAR(250),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ
);

 
-- 5. TABLA: proveedor
 

CREATE TABLE proveedor (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rnc VARCHAR(20) NOT NULL UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    nombre_comercial VARCHAR(150),
    email VARCHAR(150),
    telefono VARCHAR(25),
    direccion VARCHAR(250),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ
);


 
-- 6. TABLA: empleado
 

CREATE TABLE empleado (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    departamento_id UUID NOT NULL,
    codigo_empleado VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(80) NOT NULL,
    apellido VARCHAR(80) NOT NULL,
    cedula VARCHAR(20) NOT NULL UNIQUE,
    cargo VARCHAR(100),
    email VARCHAR(150) UNIQUE,
    telefono VARCHAR(25),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,

    CONSTRAINT fk_empleado_departamento
        FOREIGN KEY (departamento_id)
        REFERENCES departamento(id)
        ON DELETE RESTRICT
);

 
-- 7. TABLA: vehiculo
 

CREATE TABLE vehiculo (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    departamento_id UUID NOT NULL,
    tipo_combustible_id SMALLINT NOT NULL,
    placa VARCHAR(20) NOT NULL UNIQUE,
    ficha VARCHAR(30) NOT NULL UNIQUE,
    marca VARCHAR(50),
    modelo VARCHAR(50),
    anio SMALLINT,
    tipo_vehiculo VARCHAR(50),
    capacidad_tanque NUMERIC(10,2) NOT NULL,
    odometro_actual NUMERIC(12,2) NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,

    CONSTRAINT fk_vehiculo_departamento
        FOREIGN KEY (departamento_id)
        REFERENCES departamento(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_vehiculo_tipo_combustible
        FOREIGN KEY (tipo_combustible_id)
        REFERENCES tipo_combustible(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_vehiculo_capacidad_tanque
        CHECK (capacidad_tanque > 0),

    CONSTRAINT chk_vehiculo_odometro
        CHECK (odometro_actual >= 0),

    CONSTRAINT chk_vehiculo_anio
        CHECK (anio IS NULL OR anio >= 1900)
);

 
-- 8. TABLA: tanque
 

CREATE TABLE tanque (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    estacion_id UUID NOT NULL,
    tipo_combustible_id SMALLINT NOT NULL,
    codigo VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(100),
    capacidad_maxima NUMERIC(12,2) NOT NULL,
    stock_actual NUMERIC(12,2) NOT NULL DEFAULT 0,
    nivel_critico NUMERIC(12,2) NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,

    CONSTRAINT fk_tanque_estacion
        FOREIGN KEY (estacion_id)
        REFERENCES estacion(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_tanque_tipo_combustible
        FOREIGN KEY (tipo_combustible_id)
        REFERENCES tipo_combustible(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_tanque_capacidad
        CHECK (capacidad_maxima > 0),

    CONSTRAINT chk_tanque_stock_no_negativo
        CHECK (stock_actual >= 0),

    CONSTRAINT chk_tanque_stock_capacidad
        CHECK (stock_actual <= capacidad_maxima),

    CONSTRAINT chk_tanque_nivel_critico
        CHECK (
            nivel_critico >= 0
            AND nivel_critico <= capacidad_maxima
        )
);

 
-- 9. TABLA: usuario
 

CREATE TABLE usuario (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    rol_id SMALLINT NOT NULL,
    empleado_id UUID,
    estacion_id UUID,
    nombre_usuario VARCHAR(60) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    bloqueado BOOLEAN NOT NULL DEFAULT FALSE,
    intentos_fallidos SMALLINT NOT NULL DEFAULT 0,
    ultimo_acceso TIMESTAMPTZ,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,

    CONSTRAINT uq_usuario_empleado
        UNIQUE (empleado_id),

    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (rol_id)
        REFERENCES rol(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_usuario_empleado
        FOREIGN KEY (empleado_id)
        REFERENCES empleado(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_usuario_estacion
        FOREIGN KEY (estacion_id)
        REFERENCES estacion(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_usuario_intentos_fallidos
        CHECK (intentos_fallidos >= 0)
);



 
-- 10. TABLA: refresh_token
 

CREATE TABLE refresh_token (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id UUID NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    fecha_revocacion TIMESTAMPTZ,
    reemplazado_por_id UUID,
    ip_creacion VARCHAR(45),
    ip_revocacion VARCHAR(45),

    CONSTRAINT uq_refresh_token_reemplazado_por
        UNIQUE (reemplazado_por_id),

    CONSTRAINT fk_refresh_token_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_refresh_token_reemplazado_por
        FOREIGN KEY (reemplazado_por_id)
        REFERENCES refresh_token(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_refresh_token_expiracion
        CHECK (fecha_expiracion > fecha_creacion),

    CONSTRAINT chk_refresh_token_revocacion
        CHECK (
            fecha_revocacion IS NULL
            OR fecha_revocacion >= fecha_creacion
        ),

    CONSTRAINT chk_refresh_token_no_autorreferencia
        CHECK (
            reemplazado_por_id IS NULL
            OR reemplazado_por_id <> id
        )
);

 
-- 11. TABLA: solicitud
 

CREATE TABLE solicitud (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    empleado_id UUID NOT NULL,
    vehiculo_id UUID NOT NULL,
    departamento_id UUID NOT NULL,
    creada_por_usuario_id UUID NOT NULL,
    revisada_por_usuario_id UUID,
    tipo_solicitud VARCHAR(20) NOT NULL,
    cantidad_solicitada NUMERIC(10,2) NOT NULL,
    cantidad_autorizada NUMERIC(10,2),
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    fecha_solicitud TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_expiracion TIMESTAMPTZ,
    fecha_revision TIMESTAMPTZ,
    motivo_rechazo VARCHAR(300),
    motivo_cancelacion VARCHAR(300),
    observaciones VARCHAR(500),

    CONSTRAINT fk_solicitud_empleado
        FOREIGN KEY (empleado_id)
        REFERENCES empleado(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitud_vehiculo
        FOREIGN KEY (vehiculo_id)
        REFERENCES vehiculo(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitud_departamento
        FOREIGN KEY (departamento_id)
        REFERENCES departamento(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitud_creada_por
        FOREIGN KEY (creada_por_usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitud_revisada_por
        FOREIGN KEY (revisada_por_usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_solicitud_tipo
        CHECK (
            tipo_solicitud IN (
                'MANUAL',
                'AUTOMATICA',
                'RECURRENTE'
            )
        ),

    CONSTRAINT chk_solicitud_cantidad_solicitada
        CHECK (cantidad_solicitada > 0),

    CONSTRAINT chk_solicitud_cantidad_autorizada
        CHECK (
            cantidad_autorizada IS NULL
            OR cantidad_autorizada > 0
        ),

    CONSTRAINT chk_solicitud_estado
        CHECK (
            estado IN (
                'PENDIENTE',
                'APROBADA',
                'RECHAZADA',
                'CANCELADA'
            )
        ),

    CONSTRAINT chk_solicitud_rechazo
        CHECK (
            estado <> 'RECHAZADA'
            OR motivo_rechazo IS NOT NULL
        ),

    CONSTRAINT chk_solicitud_cancelacion
        CHECK (
            estado <> 'CANCELADA'
            OR motivo_cancelacion IS NOT NULL
        ),

    CONSTRAINT chk_solicitud_aprobacion
        CHECK (
            estado <> 'APROBADA'
            OR (
                cantidad_autorizada IS NOT NULL
                AND fecha_expiracion IS NOT NULL
                AND revisada_por_usuario_id IS NOT NULL
                AND fecha_revision IS NOT NULL
            )
        )
);

 
-- 12. TABLA: ticket
 

CREATE TABLE ticket (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    solicitud_id UUID NOT NULL,
    estacion_id UUID NOT NULL,
    tipo_combustible_id SMALLINT NOT NULL,
    numero_ticket VARCHAR(25) NOT NULL UNIQUE,
    cantidad_autorizada NUMERIC(10,2) NOT NULL,
    estado VARCHAR(25) NOT NULL DEFAULT 'CREADO',
    token_qr_hash VARCHAR(255) NOT NULL UNIQUE,
    firma_qr VARCHAR(255) NOT NULL,
    fecha_emision TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    fecha_envio TIMESTAMPTZ,
    fecha_anulacion TIMESTAMPTZ,
    anulado_por_usuario_id UUID,
    motivo_anulacion VARCHAR(300),

    CONSTRAINT uq_ticket_solicitud
        UNIQUE (solicitud_id),

    CONSTRAINT fk_ticket_solicitud
        FOREIGN KEY (solicitud_id)
        REFERENCES solicitud(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_ticket_estacion
        FOREIGN KEY (estacion_id)
        REFERENCES estacion(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_ticket_tipo_combustible
        FOREIGN KEY (tipo_combustible_id)
        REFERENCES tipo_combustible(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_ticket_anulado_por
        FOREIGN KEY (anulado_por_usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_ticket_cantidad
        CHECK (cantidad_autorizada > 0),

    CONSTRAINT chk_ticket_fechas
        CHECK (fecha_expiracion > fecha_emision),

    CONSTRAINT chk_ticket_estado
        CHECK (
            estado IN (
                'CREADO',
                'ENVIADO',
                'CONSUMIDO',
                'ANULADO'
            )
        ),

    CONSTRAINT chk_ticket_anulacion
        CHECK (
            estado <> 'ANULADO'
            OR (
                fecha_anulacion IS NOT NULL
                AND anulado_por_usuario_id IS NOT NULL
                AND motivo_anulacion IS NOT NULL
            )
        )
);

 
-- 13. TABLA: despacho
 

CREATE TABLE despacho (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id UUID NOT NULL,
    despachador_usuario_id UUID NOT NULL,
    tanque_id UUID NOT NULL,
    cantidad_despachada NUMERIC(10,2) NOT NULL,
    odometro_registrado NUMERIC(12,2) NOT NULL,
    fecha_despacho TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    observaciones VARCHAR(500),
    direccion_ip VARCHAR(45),

    CONSTRAINT uq_despacho_ticket
        UNIQUE (ticket_id),

    CONSTRAINT fk_despacho_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES ticket(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_despacho_usuario
        FOREIGN KEY (despachador_usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_despacho_tanque
        FOREIGN KEY (tanque_id)
        REFERENCES tanque(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_despacho_cantidad
        CHECK (cantidad_despachada > 0),

    CONSTRAINT chk_despacho_odometro
        CHECK (odometro_registrado >= 0)
);


 
-- 14. TABLA: recepcion_combustible
 

CREATE TABLE recepcion_combustible (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proveedor_id UUID NOT NULL,
    tanque_id UUID NOT NULL,
    registrada_por_usuario_id UUID NOT NULL,
    numero_factura VARCHAR(50) NOT NULL,
    cantidad_recibida NUMERIC(12,2) NOT NULL,
    fecha_recepcion TIMESTAMPTZ NOT NULL,
    observaciones VARCHAR(500),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_recepcion_proveedor_factura
        UNIQUE (proveedor_id, numero_factura),

    CONSTRAINT fk_recepcion_proveedor
        FOREIGN KEY (proveedor_id)
        REFERENCES proveedor(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_recepcion_tanque
        FOREIGN KEY (tanque_id)
        REFERENCES tanque(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_recepcion_usuario
        FOREIGN KEY (registrada_por_usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_recepcion_cantidad
        CHECK (cantidad_recibida > 0)
);

 
-- 15. TABLA: transferencia_inventario
 

CREATE TABLE transferencia_inventario (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tanque_origen_id UUID NOT NULL,
    tanque_destino_id UUID NOT NULL,
    registrada_por_usuario_id UUID NOT NULL,
    cantidad NUMERIC(12,2) NOT NULL,
    fecha_transferencia TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    observaciones VARCHAR(500),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_transferencia_tanque_origen
        FOREIGN KEY (tanque_origen_id)
        REFERENCES tanque(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_transferencia_tanque_destino
        FOREIGN KEY (tanque_destino_id)
        REFERENCES tanque(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_transferencia_usuario
        FOREIGN KEY (registrada_por_usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transferencia_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_transferencia_tanques_distintos
        CHECK (tanque_origen_id <> tanque_destino_id)
);

 
-- 16. TABLA: ajuste_inventario
 

CREATE TABLE ajuste_inventario (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tanque_id UUID NOT NULL,
    reportado_por_usuario_id UUID NOT NULL,
    revisado_por_usuario_id UUID,
    tipo_ajuste VARCHAR(20) NOT NULL,
    cantidad NUMERIC(12,2) NOT NULL,
    motivo VARCHAR(300) NOT NULL,
    estado VARCHAR(25) NOT NULL DEFAULT 'PENDIENTE',
    fecha_reporte TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_revision TIMESTAMPTZ,
    motivo_rechazo VARCHAR(300),
    observaciones VARCHAR(500),

    CONSTRAINT fk_ajuste_tanque
        FOREIGN KEY (tanque_id)
        REFERENCES tanque(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_ajuste_reportado_por
        FOREIGN KEY (reportado_por_usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_ajuste_revisado_por
        FOREIGN KEY (revisado_por_usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_ajuste_tipo
        CHECK (
            tipo_ajuste IN (
                'POSITIVO',
                'NEGATIVO'
            )
        ),

    CONSTRAINT chk_ajuste_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_ajuste_estado
        CHECK (
            estado IN (
                'PENDIENTE',
                'APROBADO',
                'RECHAZADO'
            )
        ),

    CONSTRAINT chk_ajuste_revision
        CHECK (
            estado = 'PENDIENTE'
            OR (
                revisado_por_usuario_id IS NOT NULL
                AND fecha_revision IS NOT NULL
            )
        ),

    CONSTRAINT chk_ajuste_rechazo
        CHECK (
            estado <> 'RECHAZADO'
            OR motivo_rechazo IS NOT NULL
        )
);

 
-- 17. TABLA: movimiento_inventario
 

CREATE TABLE movimiento_inventario (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tanque_id UUID NOT NULL,
    registrado_por_usuario_id UUID NOT NULL,
    tipo_movimiento VARCHAR(30) NOT NULL,
    cantidad NUMERIC(12,2) NOT NULL,
    saldo_anterior NUMERIC(12,2) NOT NULL,
    saldo_posterior NUMERIC(12,2) NOT NULL,
    recepcion_id UUID,
    despacho_id UUID,
    transferencia_id UUID,
    ajuste_id UUID,
    fecha_movimiento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    observaciones VARCHAR(500),

    CONSTRAINT fk_movimiento_tanque
        FOREIGN KEY (tanque_id)
        REFERENCES tanque(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimiento_usuario
        FOREIGN KEY (registrado_por_usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimiento_recepcion
        FOREIGN KEY (recepcion_id)
        REFERENCES recepcion_combustible(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimiento_despacho
        FOREIGN KEY (despacho_id)
        REFERENCES despacho(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimiento_transferencia
        FOREIGN KEY (transferencia_id)
        REFERENCES transferencia_inventario(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimiento_ajuste
        FOREIGN KEY (ajuste_id)
        REFERENCES ajuste_inventario(id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_movimiento_recepcion
        UNIQUE (recepcion_id),

    CONSTRAINT uq_movimiento_despacho
        UNIQUE (despacho_id),

    CONSTRAINT uq_movimiento_ajuste
        UNIQUE (ajuste_id),

    CONSTRAINT chk_movimiento_tipo
        CHECK (
            tipo_movimiento IN (
                'RECEPCION',
                'DESPACHO',
                'TRANSFERENCIA_ENTRADA',
                'TRANSFERENCIA_SALIDA',
                'MERMA',
                'AJUSTE_POSITIVO',
                'AJUSTE_NEGATIVO'
            )
        ),

    CONSTRAINT chk_movimiento_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT chk_movimiento_saldo_anterior
        CHECK (saldo_anterior >= 0),

    CONSTRAINT chk_movimiento_saldo_posterior
        CHECK (saldo_posterior >= 0),

    CONSTRAINT chk_movimiento_origen
        CHECK (
            (
                tipo_movimiento = 'RECEPCION'
                AND recepcion_id IS NOT NULL
                AND despacho_id IS NULL
                AND transferencia_id IS NULL
                AND ajuste_id IS NULL
            )
            OR
            (
                tipo_movimiento = 'DESPACHO'
                AND recepcion_id IS NULL
                AND despacho_id IS NOT NULL
                AND transferencia_id IS NULL
                AND ajuste_id IS NULL
            )
            OR
            (
                tipo_movimiento IN (
                    'TRANSFERENCIA_ENTRADA',
                    'TRANSFERENCIA_SALIDA'
                )
                AND recepcion_id IS NULL
                AND despacho_id IS NULL
                AND transferencia_id IS NOT NULL
                AND ajuste_id IS NULL
            )
            OR
            (
                tipo_movimiento IN (
                    'AJUSTE_POSITIVO',
                    'AJUSTE_NEGATIVO'
                )
                AND recepcion_id IS NULL
                AND despacho_id IS NULL
                AND transferencia_id IS NULL
                AND ajuste_id IS NOT NULL
            )
            OR
            (
                tipo_movimiento = 'MERMA'
                AND recepcion_id IS NULL
                AND despacho_id IS NULL
                AND transferencia_id IS NULL
                AND ajuste_id IS NULL
            )
        )
);




 
-- 18. TABLA: cierre_diario
 

CREATE TABLE cierre_diario (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tanque_id UUID NOT NULL,
    creado_por_usuario_id UUID NOT NULL,
    revisado_por_usuario_id UUID,
    fecha_cierre DATE NOT NULL,

    stock_inicial NUMERIC(12,2) NOT NULL,
    total_recepciones NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_transferencias_entrada NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_transferencias_salida NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_despachos NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_ajustes_positivos NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_ajustes_negativos NUMERIC(12,2) NOT NULL DEFAULT 0,

    stock_teorico_final NUMERIC(12,2) NOT NULL,
    stock_fisico_final NUMERIC(12,2) NOT NULL,
    diferencia NUMERIC(12,2) NOT NULL,

    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE_APROBACION',
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_revision TIMESTAMPTZ,
    motivo_diferencia VARCHAR(500),
    motivo_rechazo VARCHAR(300),
    observaciones VARCHAR(500),

    CONSTRAINT fk_cierre_tanque
        FOREIGN KEY (tanque_id)
        REFERENCES tanque(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_cierre_creado_por
        FOREIGN KEY (creado_por_usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_cierre_revisado_por
        FOREIGN KEY (revisado_por_usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_cierre_stock_inicial
        CHECK (stock_inicial >= 0),

    CONSTRAINT chk_cierre_totales
        CHECK (
            total_recepciones >= 0
            AND total_transferencias_entrada >= 0
            AND total_transferencias_salida >= 0
            AND total_despachos >= 0
            AND total_ajustes_positivos >= 0
            AND total_ajustes_negativos >= 0
        ),

    CONSTRAINT chk_cierre_stock_teorico
        CHECK (stock_teorico_final >= 0),

    CONSTRAINT chk_cierre_stock_fisico
        CHECK (stock_fisico_final >= 0),

    CONSTRAINT chk_cierre_estado
        CHECK (
            estado IN (
                'PENDIENTE_APROBACION',
                'APROBADO',
                'RECHAZADO'
            )
        ),

    CONSTRAINT chk_cierre_revision
        CHECK (
            estado = 'PENDIENTE_APROBACION'
            OR (
                revisado_por_usuario_id IS NOT NULL
                AND fecha_revision IS NOT NULL
            )
        ),

    CONSTRAINT chk_cierre_rechazo
        CHECK (
            estado <> 'RECHAZADO'
            OR motivo_rechazo IS NOT NULL
        )
);

 
-- 19. TABLA: notificacion
 

CREATE TABLE notificacion (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id UUID NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    mensaje VARCHAR(500) NOT NULL,
    leida BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_lectura TIMESTAMPTZ,

    CONSTRAINT fk_notificacion_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_notificacion_lectura
        CHECK (
            (leida = FALSE AND fecha_lectura IS NULL)
            OR
            (leida = TRUE AND fecha_lectura IS NOT NULL)
        )
);

 
-- 20. TABLA: audit_log
 

CREATE TABLE audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    usuario_id UUID,
    accion VARCHAR(50) NOT NULL,
    entidad VARCHAR(80) NOT NULL,
    entidad_id UUID,
    datos_anteriores JSONB,
    datos_nuevos JSONB,
    direccion_ip VARCHAR(45),
    user_agent VARCHAR(500),
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    hash_anterior VARCHAR(64),
    hash_actual VARCHAR(64) NOT NULL UNIQUE,

    CONSTRAINT fk_audit_log_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT
);

 
-- 21. TABLA: configuracion_sistema
 

CREATE TABLE configuracion_sistema (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave VARCHAR(100) NOT NULL UNIQUE,
    valor TEXT NOT NULL,
    tipo_dato VARCHAR(20) NOT NULL,
    descripcion VARCHAR(250),
    editable BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_por_usuario_id UUID,

    CONSTRAINT fk_configuracion_actualizado_por
        FOREIGN KEY (actualizado_por_usuario_id)
        REFERENCES usuario(id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_configuracion_tipo_dato
        CHECK (
            tipo_dato IN (
                'STRING',
                'INTEGER',
                'DECIMAL',
                'BOOLEAN'
            )
        )
);


COMMIT;