<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CombustibleAPI.Infrastructure</RootNamespace>
  </PropertyGroup>

  <!-- PasswordHasher<T> (Identity) e IHttpContextAccessor viven en el framework compartido ASP.NET Core -->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CombustibleAPI.Domain\CombustibleAPI.Domain.csproj" />
    <ProjectReference Include="..\CombustibleAPI.Application\CombustibleAPI.Application.csproj" />
  </ItemGroup>

</Project>
