import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { apiRequest } from '../services/apiClient'
import { useAuth } from '../context/AuthContext'

type Tank={id:string;codigo:string;nombre?:string;estacionNombre?:string;stockActual:number;capacidadMaxima:number}
type Supplier={id:string;nombre:string;rnc:string}
type Movement={id:string;tanqueCodigo:string;tipo:string;cantidad:number;saldoAnterior:number;saldoPosterior:number;fecha:string}
type Adjustment={id:string;tanqueCodigo:string;conteoFisico:number;cantidad:number;motivo:string;estado:string;fechaReporte:string;motivoRechazo?:string}

export const InventoryOperations=()=>{
 const {user}=useAuth(); const canOperate=user?.role==='ADMINISTRADOR'||user?.role==='SUPERVISOR'; const [tanks,setTanks]=useState<Tank[]>([]);const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [movements,setMovements]=useState<Movement[]>([]);const [adjustments,setAdjustments]=useState<Adjustment[]>([]);const [message,setMessage]=useState('')
 const load=async()=>{try{const [t,s,m,a]=await Promise.all([apiRequest<Tank[]>('/masters/tanques'),apiRequest<Supplier[]>('/masters/proveedores'),apiRequest<{items:Movement[]}>('/movements?pageSize=100'),apiRequest<{items:Adjustment[]}>('/adjustments?pageSize=100')]);setTanks(t.data);setSuppliers(s.data);setMovements(m.data.items);setAdjustments(a.data.items)}catch(e){setMessage(e instanceof Error?e.message:'No fue posible cargar inventario.')}}
 useEffect(()=>{void load()},[])
 async function reception(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await apiRequest('/receptions',{method:'POST',body:JSON.stringify({proveedorId:f.get('supplier'),tanqueId:f.get('tank'),numeroFactura:f.get('invoice'),cantidad:Number(f.get('amount')),fechaRecepcion:new Date().toISOString()})});setMessage('Recepción registrada.');await load();e.currentTarget.reset()}
 async function transfer(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await apiRequest('/transfers',{method:'POST',body:JSON.stringify({tanqueOrigenId:f.get('source'),tanqueDestinoId:f.get('target'),cantidad:Number(f.get('amount'))})});setMessage('Transferencia registrada.');await load();e.currentTarget.reset()}
 async function review(id:string,approve:boolean){const reason=approve?null:window.prompt('Motivo del rechazo');if(!approve&&!reason)return;await apiRequest(`/adjustments/${id}/${approve?'approve':'reject'}`,{method:'PUT',body:approve?undefined:JSON.stringify({motivo:reason})});await load()}
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-[#062d4f]">Operaciones de inventario</h1><p className="text-sm text-slate-500">Recepciones, transferencias, movimientos y ajustes.</p></div>{message&&<div className="p-3 bg-cyan-50 text-cyan-900 rounded">{message}</div>}{canOperate&&<div className="grid md:grid-cols-2 gap-5"><form onSubmit={reception} className="bg-white p-5 rounded-xl border space-y-3"><h2 className="font-bold">Registrar recepción</h2><select name="supplier" required className="w-full border p-2 rounded"><option value="">Proveedor</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.nombre} · {x.rnc}</option>)}</select><select name="tank" required className="w-full border p-2 rounded"><option value="">Tanque</option>{tanks.map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.estacionNombre}</option>)}</select><input name="invoice" required placeholder="Factura" className="w-full border p-2 rounded"/><input name="amount" required min="0.01" step="0.01" type="number" placeholder="Galones" className="w-full border p-2 rounded"/><button className="bg-[#087e8b] text-white px-4 py-2 rounded">Registrar</button></form><form onSubmit={transfer} className="bg-white p-5 rounded-xl border space-y-3"><h2 className="font-bold">Registrar transferencia</h2><select name="source" required className="w-full border p-2 rounded"><option value="">Origen</option>{tanks.map(x=><option key={x.id} value={x.id}>{x.codigo}</option>)}</select><select name="target" required className="w-full border p-2 rounded"><option value="">Destino</option>{tanks.map(x=><option key={x.id} value={x.id}>{x.codigo}</option>)}</select><input name="amount" required min="0.01" step="0.01" type="number" placeholder="Galones" className="w-full border p-2 rounded"/><button className="bg-[#087e8b] text-white px-4 py-2 rounded">Transferir</button></form></div>}<section className="bg-white rounded-xl border overflow-x-auto"><h2 className="font-bold p-4">Ajustes</h2><table className="w-full text-sm"><tbody>{adjustments.map(x=><tr key={x.id} className="border-t"><td className="p-3">{x.tanqueCodigo}</td><td>{x.conteoFisico} gal</td><td>{x.motivo}</td><td>{x.estado}</td><td>{canOperate&&x.estado==='PENDIENTE'&&<><button onClick={()=>void review(x.id,true)} className="text-emerald-700 mr-3">Aprobar</button><button onClick={()=>void review(x.id,false)} className="text-rose-700">Rechazar</button></>}</td></tr>)}</tbody></table></section><section className="bg-white rounded-xl border overflow-x-auto"><h2 className="font-bold p-4">Movimientos</h2><table className="w-full text-sm"><tbody>{movements.map(x=><tr key={x.id} className="border-t"><td className="p-3">{new Date(x.fecha).toLocaleString()}</td><td>{x.tanqueCodigo}</td><td>{x.tipo}</td><td>{x.cantidad} gal</td><td>{x.saldoAnterior} → {x.saldoPosterior}</td></tr>)}</tbody></table></section></div>
}
